import androidSeed from "./androidSeed";

export type Ingredient={id:number;name:string;category:string;is_user_created?:boolean;is_active?:boolean};
export type InventoryItem={id:number;ingredient_id:number;context_type:string;context_id:number|null;have:boolean;quantity:number|null;unit_id:number|null};
export type BarSession={id:number;name:string;session_date:string;created_at:string};
export type ShoppingItem={id:number;ingredient_id:number|null;custom_name:string|null;category:string;purchased:boolean};
export type HistoryItem={id:number;recipe_id:number;made_at:string;rating:number|null;notes:string|null};
export type RecipeMatch={recipe_id:number;recipe_name:string;status:string;missing_required:string[];available_required:string[];optional_missing:string[];substitutions:string[];quantity_issues:string[];variant_recipe_id:number|null;variant_recipe_name:string|null;explanation:string};

type State={ingredients:any[];recipes:any[];inventory:InventoryItem[];bars:BarSession[];favorites:number[];history:HistoryItem[];shopping:ShoppingItem[];backups:any[];nextIds:Record<string,number>};
const KEY="virtual-bartender-android-v1";
const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
function initial():State{return {ingredients:clone(androidSeed.ingredients),recipes:clone(androidSeed.recipes),inventory:[],bars:[],favorites:[],history:[],shopping:[],backups:[],nextIds:{ingredient:10000,recipe:10000,inventory:1,bar:1,history:1,shopping:1,backup:1}}}
function load():State{try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):initial()}catch{return initial()}}
let state=load();
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function id(kind:string){const value=state.nextIds[kind]||1;state.nextIds[kind]=value+1;return value}
const ingredient=(iid:number)=>state.ingredients.find(x=>x.id===iid);
const recipe=(rid:number)=>state.recipes.find(x=>x.id===rid);
function inventory(context_type:string,context_id:number|null){return state.inventory.filter(x=>x.context_type===context_type&&x.context_id===context_id&&x.have)}
function evaluate(r:any,items:InventoryItem[]):RecipeMatch{const have=new Set(items.map(x=>x.ingredient_id));const missing:string[]=[];const optional:string[]=[];const available:string[]=[];const substitutions:string[]=[];for(const ri of r.ingredients||[]){if(have.has(ri.ingredient_id)){if(!ri.is_optional)available.push(ri.ingredient_name);continue}const subs=(androidSeed.substitutions as any[]).filter(s=>s.required_ingredient_id===ri.ingredient_id).sort((a,b)=>a.priority-b.priority);const sub=subs.find(s=>have.has(s.substitute_ingredient_id));if(sub){const n=ingredient(sub.substitute_ingredient_id)?.name||"Substitute";substitutions.push(`${ri.ingredient_name} → ${n}`);if(!ri.is_optional)available.push(ri.ingredient_name)}else if(ri.is_optional)optional.push(ri.ingredient_name);else missing.push(ri.ingredient_name)}let status="not_makeable",explanation=`You are missing ${missing.length} required items.`;if(missing.length===0){status=substitutions.length?"substitution":"exact";explanation=substitutions.length?"You can make this using approved substitutions.":"You have all required ingredients."}else if(missing.length===1){status="almost_there";explanation="You are one required ingredient short."}return {recipe_id:r.id,recipe_name:r.name,status,missing_required:missing,available_required:available,optional_missing:optional,substitutions,quantity_issues:[],variant_recipe_id:null,variant_recipe_name:null,explanation}}
function matches(context_type:string,context_id:number|null){const inv=inventory(context_type,context_id);return state.recipes.filter(r=>r.active!==false&&!r.parent_recipe_id).map(r=>evaluate(r,inv)).filter(m=>m.status!=="not_makeable").sort((a,b)=>({exact:0,substitution:1,variant:2,almost_there:3}[a.status]??4)-({exact:0,substitution:1,variant:2,almost_there:3}[b.status]??4)||a.recipe_name.localeCompare(b.recipe_name))}
function display(rid:number,metric=false){const r=recipe(rid);if(!r)throw new Error("Recipe not found");const factor=29.5735;return {...clone(r),favorite:state.favorites.includes(rid),ingredients:(r.ingredients||[]).map((x:any)=>({ingredient_id:x.ingredient_id,name:x.ingredient_name,quantity:metric&&x.unit==="oz"&&x.quantity!=null?Math.round(x.quantity*factor*10)/10:x.quantity,unit:metric&&x.unit==="oz"?"ml":x.unit,optional:x.is_optional}))}}
function suggestions(){const by=new Map<string,any>();for(const m of matches("my_bar",null)){if(m.status!=="almost_there"||m.missing_required.length!==1)continue;const name=m.missing_required[0];const ing=state.ingredients.find(x=>x.name===name);const row=by.get(name)||{ingredient_id:ing?.id??null,ingredient_name:name,category:ing?.category||"Other",unlock_count:0,unlocks:[]};row.unlock_count++;row.unlocks.push({recipe_id:m.recipe_id,recipe_name:m.recipe_name});by.set(name,row)}return [...by.values()].sort((a,b)=>b.unlock_count-a.unlock_count||a.ingredient_name.localeCompare(b.ingredient_name))}

export const api={
 ingredients:{list:async()=>clone(state.ingredients.filter(x=>x.is_active!==false)),create:async(name:string)=>{const x={id:id("ingredient"),name:name.trim(),category:"Other",is_user_created:true,is_active:true};state.ingredients.push(x);save();return clone(x)}},
 inventory:{listMyBar:async()=>clone(inventory("my_bar",null)),listSession:async(sid:number)=>clone(inventory("tonight_bar",sid)),add:async(p:any)=>{const existing=state.inventory.find(x=>x.ingredient_id===p.ingredient_id&&x.context_type===p.context_type&&x.context_id===p.context_id);if(existing){existing.have=true;save();return clone(existing)}const x={id:id("inventory"),ingredient_id:p.ingredient_id,context_type:p.context_type,context_id:p.context_id??null,have:true,quantity:null,unit_id:null};state.inventory.push(x);save();return clone(x)},updateQuantity:async(i:number,q:number|null)=>{const x=state.inventory.find(v=>v.id===i);if(x)x.quantity=q;save();return clone(x)},remove:async(i:number)=>{state.inventory=state.inventory.filter(x=>x.id!==i);save()}},
 bars:{list:async()=>clone([...state.bars].sort((a,b)=>b.id-a.id)),create:async(name:string,date:string)=>{const x={id:id("bar"),name,session_date:date,created_at:new Date().toISOString()};state.bars.unshift(x);save();return clone(x)},copyMyBar:async(sid:number)=>{for(const item of inventory("my_bar",null)){if(!state.inventory.some(x=>x.context_type==="tonight_bar"&&x.context_id===sid&&x.ingredient_id===item.ingredient_id))state.inventory.push({...clone(item),id:id("inventory"),context_type:"tonight_bar",context_id:sid})}save()},remove:async(sid:number)=>{state.bars=state.bars.filter(x=>x.id!==sid);state.inventory=state.inventory.filter(x=>!(x.context_type==="tonight_bar"&&x.context_id===sid));save()}},
 recipes:{list:async()=>clone(state.recipes.filter(x=>x.active!==false)),get:async(rid:number)=>{const r=recipe(rid);if(!r)throw new Error("Recipe not found");return {...clone(r),favorite:state.favorites.includes(rid)}},update:async(rid:number,p:any)=>{const r=recipe(rid);if(!r)throw new Error("Recipe not found");Object.assign(r,p);save();return clone(r)},hide:async(rid:number)=>{const r=recipe(rid);if(r)r.active=false;save()}},
 display:{recipe:async(rid:number,metric=false)=>display(rid,metric)},
 favorites:{list:async()=>state.favorites.map(rid=>({recipe_id:rid,name:recipe(rid)?.name||`Recipe #${rid}`})),add:async(rid:number)=>{if(!state.favorites.includes(rid))state.favorites.push(rid);save()},remove:async(rid:number)=>{state.favorites=state.favorites.filter(x=>x!==rid);save()}},
 history:{list:async()=>clone([...state.history].sort((a,b)=>b.id-a.id)),add:async(p:any)=>{const x={id:id("history"),recipe_id:p.recipe_id,made_at:new Date().toISOString(),rating:p.rating??null,notes:p.notes??null};state.history.unshift(x);save();return clone(x)}},
 matches:{myBar:async()=>clone(matches("my_bar",null)),session:async(sid:number)=>clone(matches("tonight_bar",sid))},
 surprise:{myBar:async()=>pick(matches("my_bar",null)),session:async(sid:number)=>pick(matches("tonight_bar",sid))},
 shopping:{list:async()=>clone(state.shopping),addManual:async(name:string,category="Other")=>addShopping(null,name,category),addIngredient:async(iid:number,category="Other")=>addShopping(iid,null,category),markPurchased:async(i:number,v:boolean)=>{const x=state.shopping.find(y=>y.id===i);if(x)x.purchased=v;save()},remove:async(i:number)=>{state.shopping=state.shopping.filter(x=>x.id!==i);save()}},
 shoppingSuggestions:{myBar:async()=>clone(suggestions())},
 backups:{list:async()=>clone(state.backups.map(({snapshot,...x})=>x)),create:async()=>{const text=JSON.stringify(state);const x={id:id("backup"),created_at:new Date().toISOString(),size_bytes:new Blob([text]).size,snapshot:text};state.backups.unshift(x);save();return clone(x)},restore:async(i:number)=>{const b=state.backups.find(x=>x.id===i);if(!b)throw new Error("Backup not found");state=JSON.parse(b.snapshot);save()}},
 importer:{fromUrl:async()=>{throw new Error("Website import requires internet support and is not enabled in the offline Android build yet.")},scanCollection:async()=>{throw new Error("Bulk website import is not enabled in the offline Android build yet.")},save:async(p:any)=>{const rid=id("recipe");const ingredients=(p.ingredients||[]).map((ri:any,index:number)=>{let ing=state.ingredients.find(x=>x.name.toLowerCase()===String(ri.name||"").toLowerCase());if(!ing){ing={id:id("ingredient"),name:ri.name,category:"Other",is_user_created:true,is_active:true};state.ingredients.push(ing)}return{id:index+1,ingredient_id:ing.id,ingredient_name:ing.name,quantity:ri.quantity??null,unit:ri.unit??null,is_optional:false,notes:null}});state.recipes.push({id:rid,built_in_key:null,name:p.name,description:p.description||null,recipe_type:p.recipe_type||"cocktail",source_type:"user",instructions:Array.isArray(p.instructions)?p.instructions.join(" "):p.instructions||"",image_path:p.image_path||null,image_ai_generated:false,parent_recipe_id:null,active:true,ingredients});save();return{recipe_id:rid}}}
};
function pick(rows:RecipeMatch[]){const eligible=rows.filter(x=>["exact","substitution","variant"].includes(x.status));if(!eligible.length)throw new Error("No eligible drinks found.");return clone(eligible[Math.floor(Math.random()*eligible.length)])}
function addShopping(iid:number|null,name:string|null,category:string){if(iid&&state.shopping.some(x=>x.ingredient_id===iid))return clone(state.shopping.find(x=>x.ingredient_id===iid));const ing=iid?ingredient(iid):null;const x={id:id("shopping"),ingredient_id:iid,custom_name:name,category:category||ing?.category||"Other",purchased:false};state.shopping.push(x);save();return clone(x)}
